In [2]:
import numpy as np

# Zadanie 1: Tworzenie tablic
Zadanie: Stwórz tablicę jednowymiarową zawierającą liczby od 1 do 10.


In [3]:
def zad1():
    print(np.arange(1, 11))
    
zad1()

[ 1  2  3  4  5  6  7  8  9 10]


# Zadanie 2: Operacje na tablicach
Zadanie: Oblicz sumę, średnią, oraz odchylenie standardowe elementów tablicy z ćwiczenia 1.


In [5]:
def zad2():
    a = np.arange(1, 11)
    print(a.sum(), a.mean(), a.std())
        
zad2()

55 5.5 2.8722813232690143


# Zadanie 3: Przekształcenia tablic
Zadanie: Zmień kształt tablicy z ćwiczenia 1 na 2x5.

In [2]:
import numpy as np

In [3]:
def zad3():
    a = np.arange(1, 11)
    print(a.size)
    print(a.reshape(2, 5))
        
zad3()

10
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Zadanie 4: Indeksowanie i wycinanie
Zadanie: Z tablicy utworzonej w ćwiczeniu 3 wybierz drugi wiersz

In [13]:
def zad4():
    a = np.arange(1, 11)
    print(a.reshape(2, 5)[1])
        
zad4()

[ 6  7  8  9 10]


# Zadanie 5: Operacje na macierzach
Zadanie: Stwórz dwie macierze 3x3 i oblicz ich iloczyn.

Skorzystaj z dokumentacji numpy: https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [16]:
def zad5():
    m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    m2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
    print(np.dot(m1, m2))
    
zad5()

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


# Zadanie 6:  Generowanie danych
Zadanie: Utwórz tablicę 3x3 zawierającą losowe wartości z przedziału od 0 do 10.


In [17]:
def zad6():
    print(np.random.randint(0, 11, (3, 3)))
zad6()

[[ 3  5  9]
 [ 1  0  7]
 [10  0 10]]


# Zadanie 7: Operacje logiczne
Zadanie: Stwórz maskę logiczną dla tablicy z ćwiczenia 7, która identyfikuje wartości większe niż 5.

In [19]:
def zad7():
    tablica_7 = np.random.randint(0, 11, (3, 3))
    print(tablica_7 > 5)

zad7()

[[False False False]
 [False  True False]
 [False False False]]


# Zadanie 8:  Manipulacja danymi
Zadanie: Zastąp wszystkie wartości mniejsze niż 5 w tablicy z ćwiczenia 7 wartością -1.

In [21]:
def zad8():
    tablica_7 = np.random.randint(0, 11, (3, 3))
    tablica_7[tablica_7 < 5] = -1
    print(tablica_7)

zad8()

[[-1 10  6]
 [ 8 10 -1]
 [ 5 10  8]]
